### ISSUE TITLE
[FEATURE] Selective activation of bouncers (IP and AppSec)

### ISSUE THREAD

**Issue by Kuppit** [maxlerebourg/crowdsec-bouncer-traefik-plugin#126]
Hi there, 

**Is your feature request related to a problem? Please describe.** 🐛
Currently, I am using the iptables bouncer for IP banning in conjunction with CrowdSec. However, I am interested in utilizing the CrowdSec Traefik bouncer specifically for application security (AppSec). My challenge arises from the simultaneous operation of both bouncers. I'm finding it problematic or inefficient to have the IP bouncer active when my primary need is focused on the AppSec features of the Traefik bouncer.

**Describe the solution you'd like** ✨
I propose the introduction of more granular configuration options for enabling or disabling specific bouncer functionalities. Ideally, this would include:

- A CrowdsecIpEnabled configuration option (defaulting to true, independent of the Enabled setting) to enable or disable the IP banning features.
- A CrowdsecAppsecEnabled configuration option specifically for controlling the AppSec functionalities.

This would allow for scenarios where, for example, CrowdsecIpEnabled is set to false (disabling the bouncer as a whole), but CrowdsecAppsecEnabled is set to true, thus only activating the AppSec features of the Traefik bouncer.

Thank you very much for all that you do, and I eagerly look forward to the integration of the captcha :)

**Comment by maxlerebourg** [comment]
Hi @Kuppit, 
I will apply this behavior but not as you requested.
I'm adding a new "Appsec mode" which only applies Appsec checking (WAF).
Is this correct for what you're asking?

Thank you very much 👍

**Comment by Kuppit** [comment]
Hi Max,

Thank you so much for implementing the "Appsec mode" with the Appsec checks (WAF) as we discussed. It's exactly what we needed, and I'm really appreciative of your flexibility and understanding in making this adjustment.

I'm also thrilled about the future addition of templates (and captcha) - it's something we're really looking forward to integrating.

On another note, est-ce que c'est possible de te "sponsor" sur GitHub pour te remercier pour le travail fait sur ce middleware ? (Pas pour cette issue, mais pour le middleware globalement)

Thanks again for everything!

Best,
Kuppit

**Comment by maxlerebourg** [comment]
Perfect, it's in review step for this issue. This will be available in the next release 😉 

I don't really understand the template thing, you want the ability to respond with a "html" template when the bouncer block the request ? If so, could you create another issue, please.

For captcha, we have two PR opened by community, but I don't intend to implement that myself at the moment. Obviously, I follow update on them.

J'ai complété le formulaire github sponsor, le bouton apparaitra surement quand j'aurais été approuvé par leurs équipes.

You're welcome, this issue will be closed when the PR will be merge. Don't hesitate to put a star on it 👍
