### ISSUE TITLE
[FEATURE] Custom HTML error page integration on 403 (like Captcha but for ban)

### ISSUE THREAD

**Issue by Kuppit** [maxlerebourg/crowdsec-bouncer-traefik-plugin#130]
**Is your feature request related to a problem? Please describe.** 🐛
When a user is banned and receives a 403 Forbidden response, the lack of a customizable error page limits the ability to provide a more user-friendly or informative experience.

**Describe the solution you'd like** ✨
I propose enhancing the flexibility in handling 403 responses by allowing the integration of a custom HTML template, similar to https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/pull/121. This approach would enable the presentation of a custom HTML error page for bans, using a variable (e.g., banTemplateFile) to specify the path to the HTML file. The idea is to mirror the captcha integration method, where the captchaTemplateFile variable determines the template to be displayed during captcha challenges. By doing this, based on the type of remediation action—be it a captcha challenge or a ban—the appropriate template (captcha or ban) would be displayed to the user.

This solution would significantly enhance user experience by providing clear, actionable information or guidance specific to the reason for the ban, all while maintaining a cohesive brand experience across different types of security responses.

**Comment by mathieuHa** [comment]
Hi,

Thanks for using the plugin.  
I believe this is duable, we'll keep you updated on the progress.

Best,

**Comment by avidflyer17** [comment]
Thanks for developping this great plugin.

Do you think it will be feasible to have by default this page when you'll do it ?
![image](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/41982995/ec9b0218-19ff-4bbf-8dcc-93285e8d265e)

Regards,

**Comment by mathieuHa** [comment]
> Thanks for developping this great plugin.
> 
> Do you think it will be feasible to have by default this page when you'll do it ? ![image](https://private-user-images.githubusercontent.com/41982995/317704252-ec9b0218-19ff-4bbf-8dcc-93285e8d265e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDM0NDQsIm5iZiI6MTcxMTkwMzE0NCwicGF0aCI6Ii80MTk4Mjk5NS8zMTc3MDQyNTItZWM5YjAyMTgtMTlmZi00YmJmLThkY2MtOTMyODVlOGQyNjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE2MzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjY0MzUzNjE1YjEwYWJmMzgxYzBmOGEyY2JkMzVlNjdiYTg3NmI2YTFkZjBiNjFmOGY2Y2VlODZmYjE4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8_Az-oU2hSbH9a-noNH5Mwhw30pIg9W2ePnzww-1SS0)
> 
> Regards,

Hey,

Yes I think so because we already use a similar template for the captcha feature.  
Take a look at the [branch](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/tree/113-feature-captcha-implementation).  
Once its release should be easy to do the same.  
The choice of the template will be up to the user.

Regards
