### ISSUE TITLE
[BUG] Disabling Debug logging doesn't take effect until a Traefik restart

### ISSUE THREAD

**Issue by thespad** [maxlerebourg/crowdsec-bouncer-traefik-plugin#132]
**Describe the bug** 🐛
Switching `logLevel` from `INFO` to `DEBUG` immediately enables debug log output, but switching *back* to `INFO` continues to produce debug output until Traefik is restarted

**Expected behavior** 👀
Log level behaviour should be consistent

**Context** 🔎

**Version (please complete the following information):**
 - OS: Docker
 - Traefik version: 2.10.7
 - Plugin version: 1.2.0-rc2
 - Redis: 7.2.4

**To Reproduce**
1. Start tailing Traefik logs
2. Change `logLevel` from `INFO` to `DEBUG`
3. Observe logs change to include debug output
4. Change `logLevel` from `DEBUG` to `INFO`
5. Observe logs do not stop including debug output

**Comment by maxlerebourg** [comment]
Can you test version 1.2.1-rc1 and tell us if it solves your issue?

**Comment by thespad** [comment]
Looks like that's sorted it, thanks.
