### ISSUE TITLE
[BUG] Documentation error (not captchaHTMLFilePath but banHTMLFilePath) in Middleware settings

### ISSUE THREAD

**Issue by avidflyer17** [maxlerebourg/crowdsec-bouncer-traefik-plugin#146]
**Describe the bug** 🐛
Error in documentation

**Expected behavior** 👀
it's not captchaHTMLFilePath but banHTMLFilePath ;)

**Context** 🔎
![image](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/41982995/910f670f-4c3e-4030-85c7-93dc6ba446a3)
**Version (please complete the following information):**
N/A

**To Reproduce**
1. Follow documentation

**Comment by avidflyer17** [comment]
With ban, it's working : 
![CrowdSec Access Forbidden](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/41982995/7efb065a-fae7-4b82-b3ee-7e9ad0358b79)

**Comment by mathieuHa** [comment]
Hi @avidflyer17 
Thank you for noticing, I'll update it right away.
