### ISSUE TITLE
[FEATURE] AppSec support user-agent passthrough

### ISSUE THREAD

**Issue by LaurenceJJones** [maxlerebourg/crowdsec-bouncer-traefik-plugin#148]
**Is your feature request related to a problem? Please describe.** 🐛

Hey team 👋🏻 at CrowdSec we found an unfortunate bug that caused an issue with the way that AppSec was handling the user-agent off the client. From `1.6.1` we will support a [new header](https://github.com/crowdsecurity/crowdsec/blob/2291a232cb7188862bd1976615a19835e0f94ad2/pkg/appsec/request.go#L25) that will ensure the actual client user agent is properly parsed and handled.

We plan to publish `1.6.1` soon so I thought I would make you aware of the issue so this plugin can be update by the time it is released

**Describe the solution you'd like** ✨
Add the user-agent to the corresponding header that is passed to the AppSec component

**Comment by mathieuHa** [comment]
Hi @LaurenceJJones Thanks for letting us know in advance, I opened a PR to update to add the header "User-Agent"
Can we merge before release 1.6.1 of Crowdsec  or should we wait ?

**Comment by LaurenceJJones** [comment]
> Hi @LaurenceJJones Thanks for letting us know in advance, I opened a PR to update to copy the header `User-Agent` with `X-Crowdsec-Appsec-User-Agent` before sending to AppSec. Can we merge before release 1.6.1 of Crowdsec or should we wait ?

Up to you if you push the merge now it may conflict with some rules that check for "non-whitelisted" headers we have a testing session coming up shortly for `1.6.1` so we should be able to give you a definite date from there
