### ISSUE TITLE
[Question] Is local cache realy a filesystem cache?

### ISSUE THREAD

**Issue by trunneml** [maxlerebourg/crowdsec-bouncer-traefik-plugin#172]
The documentation says that the local cache uses the filesystem, but I can't the filesystem call in the code. As far as I understand github.com/leprosus/golang-ttl-map is a in memory map that is used as local cache. So is it possible that the documentation is wrong and the local cache is an in memory cache?

**Comment by mathieuHa** [comment]
Hello @trunneml,

You are right.  

We will clarify that.
