### ISSUE TITLE
[BUG] CrowdsecAppsecFailureBlock false should also not block when crowdsec is down

### ISSUE THREAD

**Issue by trunneml** [maxlerebourg/crowdsec-bouncer-traefik-plugin#173]
**Describe the bug** 🐛
Setting `CrowdsecAppsecFailureBlock` to `false` works for 500, but if a connection to crowdsec is not possible crowdsec-bouncer-traefik-plugin still returns 403

**Expected behavior** 👀
When crowdsec api is not available and `CrowdsecAppsecFailureBlock` is set to `false` Traefik should just work as normal.

**To Reproduce**
1. Configure crowdsec-bouncer-traefik-plugin with CrowdsecAppsecFailureBlock set to false
2. Stop crowdsec
3. Try to open a service behinde Traefik

**Comment by maxlerebourg** [comment]
Hey @trunneml
I looked into the code, the `CrowdsecAppsecFailureBlock: false` handle the appsec response status code 500 only. We followed the [protocol](https://docs.crowdsec.net/docs/next/appsec/protocol) from Crowdsec to implement our plugin.

I don't know if it's smart to totally bypass our plugin when crowdsec is unreachable.

We could add a new variable `CrowdsecAppsecUnreachableBlock` to handle this case, and by default is true.

What do you think ?

**Comment by trunneml** [comment]
An extra flag fixes my problem. 
Background: Croudsec LAPI is in an different network segment.
