### ISSUE TITLE
[FEATURE] Appsec and Stream/Live mode together.

### ISSUE THREAD

**Issue by loukaniko85** [maxlerebourg/crowdsec-bouncer-traefik-plugin#182]
Is it possible to have both modes concurrently with this plugin?

**Comment by mathieuHa** [comment]
Hi @loukaniko85,

Yes it is possible, you can enable streamMode and appsec with the following conf:

```
      # Choose stream mode
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecmode=stream"
      # Enable AppSec
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsecenabled=true"
      # Define AppSec host and port informations
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsechost=crowdsec:7422"
     
```
The `crowdsecmode=appsec`, only intend to use appsec blocking feature and not the log analysis/blocking feature that you get with live and stream mode.

Our example on appsec can give you some hints:
https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/tree/main/examples/appsec-enabled

**Comment by loukaniko85** [comment]
Thank you! I obviously missed this when the WAF feature was implemented.
