### ISSUE TITLE
[FEATURE] Define mode for Lapi not reachable

### ISSUE THREAD

**Issue by Y0ngg4n** [maxlerebourg/crowdsec-bouncer-traefik-plugin#191]
**Is your feature request related to a problem? Please describe.** 🐛
It would be very nice to have a setting to change the mode if Lapi is not reachable to just pass all traffic. Currently if Lapi is not reachable and stream mode is selected the middleware returns a 403. This is not the expected behaviour in many situations as you will block every request just if your crowdsec is down. It would be nice to have something like "CordsecLapiFailureMode" with the modes like "block" and "pass"  to have the services still online if crowdsec fails

**Describe the solution you'd like** ✨
A setting the define the mode if crowdsex Lapi is down

**Comment by mathieuHa** [comment]
Hi,

When using stream mode you can use the setting `UpdateMaxFailure`=-1 to never block when you can't reach the LAPI.

Or you may use any high number like 1440 which with default `UpdateIntervalSeconds`=60s would only start to block after 24h without being able to reach the LAPI. This can help you detect Crowdsec failure while allowing request during short upgrades or maintenances periods.

```
UpdateMaxFailure

    int64
    default: 0
    Used only in stream and alone mode, the maximum number of time we can not reach Crowdsec before blocking traffic (set -1 to never block)
```

**Comment by Y0ngg4n** [comment]
@mathieuHa ah thanks!
