### ISSUE TITLE
[BUG] warnings in crowdsec LAPI when the plugin makes queries since #192

### ISSUE THREAD

**Issue by Alaith** [maxlerebourg/crowdsec-bouncer-traefik-plugin#194]
**Describe the bug** 🐛
Since #192, the crowdsec LAPI will log warnings about a "bad user agent" on requests from the plugin.

e.x.:
```
time="2024-10-20T16:37:49Z" level=warning msg="bad user agent 'Crowdsec bouncer Traefik Plugin'" ip=172.19.0.24 name=traefik
```

**Expected behavior** 👀
The plugin uses a "good" user agent which does not trigger warnings in crowdsec.

**Context** 🔎
I use a very basic configuration for the plugin and traefik. Nearly equivalent to the basic docker-compose in the project root.

**Version (please complete the following information):**
 - OS: Docker
 - Traefik version: 3.1.6
 - Plugin version: v1.3.4
 - Redis ? : None

**To Reproduce**
1. Run the project [docker-compose.yml](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/blob/v1.3.4/docker-compose.yml) **with plugin version updated** to v1.3.4
2. Send requests to whoami
3. View warnings in crowdsec container logs

**Comment by mathieuHa** [comment]
Hi,
 Thanks for reporting this, it wasn't intended when we updated the plugin with a custom user agent.

I found the crowdsec code that "validates" user agent:

```
useragent := strings.Split(c.Request.UserAgent(), "/")
		if len(useragent) != 2 {
			logger.Warningf("bad user agent '%s'", c.Request.UserAgent())
			useragent = []string{c.Request.UserAgent(), "N/A"}
		}
```

I think I'll replace it with `Crowdsec bouncer Traefik Plugin/1.3.5` and release a new version.  
Apologies for the noises introduced.

**Comment by Alaith** [comment]
Thanks for looking into it and developing a fix so quickly!

It seems that Crowdsec's validation logic doesn't adhere to the format for User-Agent headers definied in [RFC9110 HTTP Semantics in section 10.1.5](https://www.rfc-editor.org/rfc/rfc9110.html#section-10.1.5). 

The User-Agent string you've proposed will work for the crowdsec logic. If you want to adhere to the RFC, the product identifier should be a `token` which are "short textual identifiers that do not include whitespace or delimiters." So something like: `crowdsec-bouncer-traefik-plugin/1.3.5`

**Comment by mathieuHa** [comment]
Interesting, thanks, I removed whitespaces, while we find a solution to get the version manually or to update it automatically (github action or something), I added _1.X.X_ for the version.  

@maxlerebourg will review tomorow and I'll probably release tomorow night
