### ISSUE TITLE
[BUG] LAPI Connection refused

### ISSUE THREAD

**Issue by RT-Tap** [maxlerebourg/crowdsec-bouncer-traefik-plugin#196]
**Describe the bug** 🐛
I am trying to get this plugin working however every time I try to test it by making a request to a service that uses the plugin middleware I get this error: 

```
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/10/27 02:07:13 ServeHTTP:handleNoStreamCache ip:2...1 isBanned:t crowdsecQuery:unreachable url:http://crowdsec.localnet:8089/v1/decisions?ip=2...1&banned=true Get "http://crowdsec.localnet:8089/v1/decisions?ip=2...1&banned=true": dial tcp 192.168.30.11:8089: connect: connection refused
```
with context
```
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/10/27 02:07:13 ServeHTTP ip:2...1 isTrusted:false
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/10/27 02:07:13 cache:Get key:2...1	
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/10/27 02:07:13 ServeHTTP:Get ip:2...1 isBanned:false cache:miss
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/10/27 02:07:13 ServeHTTP:handleNoStreamCache ip:2...1 isBanned:t crowdsecQuery:unreachable url:http://crowdsec.localnet:8089/v1/decisions?ip=2...1&banned=true Get "http://crowdsec.localnet:8089/v1/decisions?ip=2...1&banned=true": dial tcp 192.168.30.11:8089: connect: connection refused
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/10/27 02:07:13 handleRemediationServeHTTP ip:2...1 remediation:t
```

I have other bouncers that are registered and work fine.

When I curl from the same host I get following so doesn't seem to be connectivity issue:
`{"message":"access forbidden"}`

Logs for crowdsec LAPI show the request made using curl but absolutely no requests coming from the plugin itself.

**Context** 🔎
```
http:
  middlewares:
    crowdsec:
      plugin:
        crowdsecbouncer:
          enabled: true
          logLevel: DEBUG
          updateIntervalSeconds: 60
          updateMaxFailure: 0
          defaultDecisionSeconds: 60
          httpTimeoutSeconds: 10
          crowdsecMode: live
          crowdsecLapiKey: "k...k"
          crowdsecLapiHost: crowdsec.localnet:8089
          crowdsecLapiScheme: http
          crowdsecLapiTLSInsecureVerify: true
          clientTrustedIPs:
            - 192.168.1.0/24
          remediationHeadersCustomName: cs-remediation
          redisCacheEnabled: true
          redisCacheHost: "redis.localnet:6379"
          redisCachePassword: "z...g"
          redisCacheDatabase: "4"
```

I've played with the config a bunch so this doesnt reflect everything I've tried just the current state of affairs, no matter what I cant seem to log a request from the plugin to the LAPI

**Version (please complete the following information):**
 - OS:  Arch
 - Traefik version: 3.0.0-rc3
 - Plugin version: 1.3.5

**Comment by RT-Tap** [comment]
It was a configuration error.  Don't try to debug things at 4am.

**Comment by Crowley723** [comment]
> It was a configuration error. Don't try to debug things at 4am.

What did you end up doing to fix the issue? I am having the same problem.

**Comment by RT-Tap** [comment]
I'm sorry I don't remember at this point, but based off my closing comment with lack of additional information I think it was a trivial config issue.  I also tried checking notes I have on crowdsec and didn't leave anything in their either so only advice I have is to go back and check your config against the documentation for any discrepancies.

**Comment by Crowley723** [comment]
> I'm sorry I don't remember at this point, but based off my closing comment with lack of additional information I think it was a trivial config issue. I also tried checking notes I have on crowdsec and didn't leave anything in their either so only advice I have is to go back and check your config against the documentation for any discrepancies.

Thanks for the reply. I ended up going in a different direction and using https://github.com/fbonalair/traefik-crowdsec-bouncer. While its not maintained anymore, it worked like a charm. I'm hoping that when this plugin gets added to the crowdsec docs (There is an open pr on this repo) there is more information regarding getting started.
Thanks again.

**Comment by mathieuHa** [comment]
Hi @Crowley723,

You can find many getting started linked in the README, and specific working examples in the `https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/tree/main/examples` folder.

I understand it can be difficult to find the right options to use when you are starting with Traefik, Crowdsec or Docker but feel free to open an issue with the configuration that was problematic, we can take a look.

Also enabling debug mode of the plugin (not Traefik) show common errors and helps fixe LAPI connection refused 95% of the time.
