### ISSUE TITLE
Maybe a BUG or I do something wrong / Captcha

### ISSUE THREAD

**Issue by allroundtechie** [maxlerebourg/crowdsec-bouncer-traefik-plugin#198]
Hi there,

first I want to thank you for this awesome piece of software. I implemented this bouncer during the weekend and it works perfect except one feature which I do not get working: Captcha

My setup:
Traefik: 3.2.1
Crowdsec: 1.6.3
Crowdsec bouncer traefik plugin: 1.3.5

Everything is deployed as docker containers managed by Hashicorp Nomad.

I implemented it like described in your documentation, added the ban.html and captcha.html into traefik etc.
The decisions also work perfectly, but when I try to use the captcha instead of the ban decision I get also presented the right captcha.html but that is it, no captcha provider (I tried Cloudflare turnstile and Hcaptcha) works.
I get the following error from the logs (log level pushed to debug).

2024-11-25 11:44:00.995	
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/11/25 11:44:00 captcha:Validate invalid method: GET
2024-11-25 11:44:00.995	
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/11/25 11:44:00 captcha:Check ip:ADDRESS pass:false
2024-11-25 11:44:00.995	
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/11/25 11:44:00 cache:Get key:ADDRESS_captcha
2024-11-25 11:44:00.995	
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/11/25 11:44:00 handleRemediationServeHTTP ip:ADDRESS remediation:c
2024-11-25 11:44:00.995	
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/11/25 11:44:00 ServeHTTP ip:ADDRESS cache:hit isBanned:c
2024-11-25 11:44:00.995	
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/11/25 11:44:00 cache:Get key:ADDRESS
2024-11-25 11:44:00.995	
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/11/25 11:44:00 ServeHTTP ip:ADDRESS isTrusted:false

The logs are in order from latest to oldest.
The only error I see is (which is the last message I get):
captcha:Validate invalid method: GET

On client side I get the captcha.html presented
![Screenshot from 2024-11-25 14-16-23](https://github.com/user-attachments/assets/f99be06a-8c64-4b65-ab6e-6bd94fe51020)
 but without the box from the captcha provider.
In Chrome developer tools console I get:
Uncaught SyntaxError: Unexpected token '<'

This is the only error I see on client side.
I am running out of ideas, searched through all issues in this repository and also google did not come up with something useful, at least not for me, I am an IT guy all my life but not a developer.
Any idea what could cause this behavior or what the root cause might be?
Thanks in advance.

**Comment by maxlerebourg** [comment]
Hello, thanks for the good words.
Can you share your configuration ? Obviously, hide the CaptchaSiteKey and the CaptchaSecretKey.

**Comment by allroundtechie** [comment]
I use the cli arguments to configure traefik except the dynamic part inside the nomad job file:
task "traefik" {
      driver = "docker"
      config {
        image = "traefik:3.2.1"
        ports = ["80", "443", "ping"]
        args = [
          "--accesslog=true",
          "--api.dashboard=false",
          "--certificatesresolvers.letsencrypt.acme.dnschallenge=true",
          "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=PROVIDER",
          "--certificatesresolvers.letsencrypt.acme.email=EMAIL",
          "--certificatesresolvers.letsencrypt.acme.keytype=RSA4096",
          "--certificatesresolvers.letsencrypt.acme.storage=/acme/letsencrypt.json",
          "--certificatesresolvers.vault.acme.caserver=URL",
          "--certificatesresolvers.vault.acme.email=EMAIL",
          "--certificatesresolvers.vault.acme.httpchallenge.entrypoint=internal",
          "--certificatesresolvers.vault.acme.storage=/acme/vault.json",
          "--entrypoints.80.address=:80",
          "--entrypoints.80.http.redirections.entryPoint.to=443",
          "--entrypoints.80.http.redirections.entryPoint.scheme=https",
          "--entrypoints.80.http.redirections.entrypoint.permanent=true",
          "--entrypoints.443.address=:443",
          "--entryPoints.ping.address=:8082",
          "--experimental.plugins.bouncer.moduleName=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin",
          "--experimental.plugins.bouncer.version=v1.3.5",
          "--ping.entryPoint=ping",
          "--providers.consulcatalog=true",
          "--providers.consulcatalog.endpoint.address=IP:8500",
          "--providers.consulcatalog.exposedByDefault=false",
          "--providers.file.filename=/configuration/dynamic.yml"
          ]

Traefik dynamic config:

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      curvePreferences:
        - CurveP384
        - CurveP521
      sniStrict: true

http:
  middlewares:
    crowdsec:
      plugin:
        bouncer:
          Enabled: true
          LogLevel: ERROR
          DefaultDecisionSeconds: 60
          HTTPTimeoutSeconds: 20
          CrowdsecMode: live
          CrowdsecLapiHost: FQDN
          CrowdsecLapiKey: "SECRET"
          CrowdsecLapiScheme: https
          CrowdsecLapiTLSInsecureVerify: true
          BanHTMLFilePath: /ban.html
          CaptchaProvider: turnstile
          CaptchaSiteKey: "KEY"
          CaptchaSecretKey: "SECRET"
          CaptchaGracePeriodSeconds: 1800
          CaptchaHTMLFilePath: /captcha.html

The content of the ban.html and captcha.html were copied from this respository (which are also part of the nomad job file).

**Comment by maxlerebourg** [comment]
Can you look in the html if the siteKey is filled ? 
How do you handle the content of captcha.html in your nomad conf. Maybe the siteKey vars templating is interpoled before it used by the plugin.
I will look into this, this evening. This is my first supposition here, but more I have data, more I can help you.

**Comment by allroundtechie** [comment]
To summarize and also provide a solution for others who maybe run into this issue:
If you want to have the captcha.html content as a template in the nomad job you need to modify three parts of the html code like this:
'<script src="{{"{{"}} .FrontendJS {{"}}"}}" async defer></script>'

which will then result in the traefik container like

https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/blob/main/captcha.html#L280

The other part is:
'<div id="captcha" class="{{"{{"}} .FrontendKey {{"}}"}}" data-sitekey="{{"{{"}} .SiteKey {{"}}"}}" data-callback="captchaCallback">'

which will then result in the traefik container like

https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/blob/main/captcha.html#L297C8-L297C116

With these three changes it works like a charme.
