### ISSUE TITLE
Implement shared cache with an external redis as an option

### ISSUE THREAD

**Issue by mathieuHa** [maxlerebourg/crowdsec-bouncer-traefik-plugin#20]
When https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/issues/18 is resolved, it will be easy to deal with shared cache.

This can be usefull if the cache is filled with many IP or if we want to use it for many Traefik instances using the same crowdsec and redis cache instance.

**Comment by aleksandarmomic** [comment]
Eagerly waiting for this one!
