### ISSUE TITLE
Cannot get Plugin get to work

### ISSUE THREAD

**Issue by KevinLiss** [maxlerebourg/crowdsec-bouncer-traefik-plugin#201]
Hi, i cannot get my plugin to work, the moment i enabling the plugin in dynamic configuration in traefik, all requests are blocked, except the "clientTrustedIPs"

my compose.yml with traefik and crowdsec:

    traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    network_mode: host
    depends_on:
      - crowdsec
    security_opt:
      - no-new-privileges:true
    mem_limit: 1G
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/logs/:/var/log/traefik
      - ./config/traefik/letsencrypt:/letsencrypt
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/traefik/config.yml:/etc/traefik/config.yml
    environment:
      - NETCUP_CUSTOMER_NUMBER=
      - NETCUP_API_KEY=
      - NETCUP_API_PASSWORD=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "150m"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.middlewares=ipallow@file
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.rule=Host()
    
    crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:latest
    restart: always
    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve"
      GID: "${PGID}"
      BOUNCER_KEY_TRAEFIK: ${CROWDSEC_BOUNCER_API_KEY}
    networks:
      - nike
    volumes:
      - ./config/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./config/traefik/logs:/var/log/traefik:ro
      - ./config/crowdsec/db:/var/lib/crowdsec/data/
      - ./config/crowdsec/config:/etc/crowdsec/

traefik.yml snippet

    accessLog:
      filePath: "/var/log/traefik/access.log"
    
    experimental:
      plugins:
        crowdsec-bouncer:
          moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
          version: "v1.3.5"
          
        entrypoints:
          https:
            address: "0.0.0.0:443"
            http:
              middlewares:
                - crowdsec-bouncer@file
              tls:
                certResolver: letsencrypt
                domains:

traefiks config.yml

    http:
      middlewares:
        ipallow:
          ipAllowList:
            sourceRange:
              - "192.168.178.0/24"
              - "172.23.0.0/16"

    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer:
          enabled: false # change to true
          logeLevel: DEBUG
          crowdsecMode: live
          crowdsecLapiHost: crwodsec:8080
          crowdsecLapiScheme: http
          crowdsecLapiTLSInsecureVerify: false
          crowdsecLapiKey: 
          clientTrustedIPs: 
            - "192.168.178.1/24"
          crowdsecAppsecEnabled: false

bouncer key i've got from crowdsec "cscli bouncer add traefik_bouncer" and its the same in crowdsecLapiKey in config.yml as in docker-compose as

**Comment by maxlerebourg** [comment]
Where are our log, we ask it in the issue template...
+ be careful here, you have a typo: logeLevel: DEBUG
