### ISSUE TITLE
Anyone have it working on kubernetes?

### ISSUE THREAD

**Issue by mannp** [maxlerebourg/crowdsec-bouncer-traefik-plugin#40]
I have the plugin configured (I think) but am not sure if I will see the plugin in my local traefik dashboard or not?

Being a plugin I am also not clear on how to debug it, as the logs seem fine.

I ask as I configured my middleware without an api key and the traefik hub is showing the plugin as connected and healthy?

Apologies for the noob questions.

**Comment by mathieuHa** [comment]
Hi @mannp 

Thank you for your question,

We'll try to add an example for Kubernetes with Traefik as Ingress Controller and a Traefik/Whoami container protected by Crowdsec

We'll keep you updated in the following week,

Best,
Mathieu

**Comment by mannp** [comment]
> Hi @mannp
> 
> Thank you for your question,
> 
> We'll try to add an example for Kubernetes with Traefik as Ingress Controller and a Traefik/Whoami container protected by Crowdsec
> 
> We'll keep you updated in the following week,
> 
> Best, Mathieu

Hi @maxlerebourg that would be very helpful, thanks 👍🏻

**Comment by mmetc** [comment]
Hi,

I'm interested too, because I'd like to add support for your middleware to the crowdsec helm charts. Also to test the TLS support that I'm preparing in a separate PR.

**Comment by mannp** [comment]
So, made some progress and have everything sort of working.

Traefik is now happy and the plugin appears to now be routing packets, but when I ban my ip I am not banned.

Investigating if I the plugin is seeing the wrong ip.....its odd as crowdsec appears to be seeing the right one though.

**Comment by maxlerebourg** [comment]
Hi @mmetc, can you submit your 2 PR if they are terminated.

@mannp, you can enable more logging with `logLevel: DEBUG` but if what you said is right, there is a big problem with our plugin 😉

**Comment by mathieuHa** [comment]
> So, made some progress and have everything sort of working.
> 
> Traefik is now happy and the plugin appears to now be routing packets, but when I ban my ip I am not banned.
> 
> Investigating if I the plugin is seeing the wrong ip.....its odd as crowdsec appears to be seeing the right one though.
> 
> Sorted with some trusted ips added...all working now :)

I'm glad to know you made it work eventually
Indeed for some cases you need to tell Traefik to trust client IP at the entrypoint level
https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers

We added an example for this in the exemples/behind-proxy directory.

Please let me know if i'm correct and everything is working on your side.

I'll keep this issue updated, I'm writing the kubernetes documentation at the moment and will close when released

**Comment by mathieuHa** [comment]
Hey, Just added the kubernetes exemple which closed this issue on merge, dont hesitate to reopen if you encounter any issue.
