### ISSUE TITLE
Feature: Read crowdsecLapiKey from file

### ISSUE THREAD

**Issue by rwjack** [maxlerebourg/crowdsec-bouncer-traefik-plugin#44]
Quick thought, it might be a good idea to have this variable readable from a file on the local filesystem, since dynamic traefik configurations usually reside in git repositories, and pushing API keys to git services is a big no no.

**Comment by mathieuHa** [comment]
Resolved when #53 merges

I added the ability to read from files for certificates and as well for the LAPI key

**Comment by rwjack** [comment]
Awesome! I've also been looking into using tls for the traefik<->crowdsec communication, so this kills two flies with one swing.

**Comment by mathieuHa** [comment]
Version 1.1.6 has this feature, closing to clean a bit
