### ISSUE TITLE
Support version 3.X of Traefik

### ISSUE THREAD

**Issue by mathieuHa** [maxlerebourg/crowdsec-bouncer-traefik-plugin#63]
After upgrading to v3.0.0-beta2, we encounter panics

![image](https://user-images.githubusercontent.com/16974644/209581790-8cf99f20-f26a-40aa-97d1-42d5f629ba38.png)

This problem could come from Traefik or the plugin might need some adaptation.

**Comment by ashuio** [comment]
This enhancement would be really appreciated

**Comment by mathieuHa** [comment]
> This enhancement would be really appreciated

Hello @ashuio, Thanks for your interest, we'll give it another try soon, and take you updated!

Best,
Mathieu

**Comment by mathieuHa** [comment]
Hey, after somes tests we have'nt reproduced this error.

We have a version of the plugin working with `v3.0.0-beta2`

I will close now, and reopen if new error arrise
