### ISSUE TITLE
Several TrustedIPs in docker-compose

### ISSUE THREAD

**Issue by Aeon512** [maxlerebourg/crowdsec-bouncer-traefik-plugin#66]
**Describe the bug**
Hi, I tried to add several IP networks as trusted IPs within the `docker-compose.yml` file but neither worked
```
 - "traefik.http.middlewares.crowdsec.plugin.bouncer.clienttrustedips=192.168.a.0/24, 172.16.b.0/24"
 - "traefik.http.middlewares.crowdsec.plugin.bouncer.clienttrustedips=192.168.a.0/24 172.16.b.0/24 "
 - "traefik.http.middlewares.crowdsec.plugin.bouncer.clienttrustedips=[192.168.a.0/24, 172.16.b.0/24]"
```

What would be the correct syntax at all?

**Comment by mathieuHa** [comment]
Hi, 

We use the same **parser** for IP addresses that Traefik uses for the ratelimit middleware [doc.traefik.io/traefik/middlewares/http/ratelimit](https://doc.traefik.io/traefik/middlewares/http/ratelimit/#ipstrategyexcludedips)
You can find an example of syntax there.

This accepts IP, or IP ranges using CIDR.

Correct syntax would be the first one:
` - "traefik.http.middlewares.crowdsec.plugin.bouncer.clienttrustedips=192.168.a.0/24, 172.16.b.0/24"`

In fact when the plugin is started with **debug** logs It will show what `IP` or `IP range` has been parsed correctly.

```golang
logger.Debug(fmt.Sprintf("IP %v is trusted", ipAddr))
```
```golang
logger.Debug(fmt.Sprintf("IP network %v is trusted", ipAddr))
```

For instance on my Traefik it shows:
`DEBUG: CrowdsecBouncerTraefikPlugin: 2022/12/27 15:17:31 IP network 8.X.X.X/32 is trusted`

To enable **debug** logs you can use:
` - "traefik.http.middlewares.crowdsec.plugin.bouncer.loglevel=DEBUG"`

Also, you should check that Traefik is seeing your Real IP (that will be transmitted to Crowdsec), or you might have to play with [doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers](https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers)

With Debug logs, you see the IP that are transmitted:
```
DEBUG: CrowdsecBouncerTraefikPlugin: 2022/12/28 09:27:52 ServeHTTP ip:8.X.X.56 isTrusted:true
DEBUG: CrowdsecBouncerTraefikPlugin: 2022/12/28 09:27:53 ServeHTTP ip:8.X.X.47 isTrusted:false
```

Please let us know if that helps,

Mathieu

**Comment by Aeon512** [comment]
Hi Mathieu,

i tried that variant but I receive the following debug output 

DEBUG: CrowdsecBouncerTraefikPlugin: 2022/12/28 10:21:39 IP network 192.168.a.0/24 is trusted
INFO: CrowdsecBouncerTraefikPlugin: 2022/12/28 10:21:39 New:validateParams ClientTrustedIPs must be a list of IP/CIDR :parsing CIDR trusted IPs <nil>: invalid CIDR address:  172.16.b.0/24

The same parameters work for other ranges in traefik without issues… any ideas?

**Comment by mathieuHa** [comment]
Hello, 
Can you try without spaces between the IP addresses ?

like this:
`      - "traefik.http.middlewares.crowdsec-bar.plugin.bouncer.clienttrustedips=192.168.2.0/24,172.16.3.0/24"`

I'll look if I can trim spaces so it accept both syntaxes.

Best,
Mathieu

**Comment by mathieuHa** [comment]
I've added a fix that has been merged into main.


I'll keep you updated when a new release is out with this new feature, in the meantime you can remove manually spaces betweens IP ranges.

**Comment by Aeon512** [comment]
Hi Mathieu,

> Hello, Can you try without spaces between the IP addresses ?
> 
> like this: ` - "traefik.http.middlewares.crowdsec-bar.plugin.bouncer.clienttrustedips=192.168.2.0/24,172.16.3.0/24"`

I can confirm that this works. Thanks for the quick fix.

**Comment by mathieuHa** [comment]
Hey,

Stable release `1.1.7` is out now with the fix for this issue.

I'll close as completed now, feel free to open a new one if you encounter any other issue.
If you like the project, consider starring it so you get updates on new releases and we get some more visibility :)

Best,
Mathieu
