### ISSUE TITLE
[FEATURE] Redis password support

### ISSUE THREAD

**Issue by Allram** [maxlerebourg/crowdsec-bouncer-traefik-plugin#86]
**Describe the bug** 🐛
How do you connect to a Redis instance with a Redis password? and chose Redis DB?

**Expected behavior** 👀
Connection established.

**Context** 🔎
Trying to connect to my Redis instance which is running AUTH with password. Tried different connectionstrings, but noone seems to work.
t.ex:
redis://:PASSWORD@redis:6379/5
redis://:PASSWORD@redis:6379/5
:PASSWORD@redis:6379
:PASSWORD@redis:6379/5

**Version (please complete the following information):**
 - OS: Docker @UnRaid
 - Traefik version: 2.9
 - Plugin version: 1.1.10
 - Redis ? :7.0.4

**Comment by Allram** [comment]
And also if redis.sock could be used instead of only TCP, but that is not a very important feature.
It's better to get the availability to connect with a password.

**Comment by Allram** [comment]
No problem! 
This plugin works great as it is.
So just adding Redis password would solve everything for me, the other things is just "if possible aaaaaand don't take to much time".  :)

**Comment by mathieuHa** [comment]
Hello @Allram 

Thanks for using this plugin,
We are reviewing currently the support for password use in #87 
We'll keep you updated when a new release ships with it.

We'll also take a look at connexion scheme with socket, maybe it's easier than we imagined,

Best,
Mathieu

**Comment by Sblop** [comment]
> And also if redis.sock could be used instead of only TCP, but that is not a very important feature. It's better to get the availability to connect with a password.
> 
> Maybe also defining the database could be implemented? / after the connection URl t.ex: redis://user:password@redis:6379/5

+1 for database selection in redis, like redis:port/number, that is the standard implementation.

/B

**Comment by maxlerebourg** [comment]
For database selection, see the [issue 99](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/issues/99), this will be released soon, after code review.

Max
