### ISSUE TITLE
[BUG] RedisPassword with 1.1.11-beta

### ISSUE THREAD

**Issue by Allram** [maxlerebourg/crowdsec-bouncer-traefik-plugin#88]
Hello,

Thanks for trying to get RedisPasswords to work.
It seems like the plugin can get an connection to the Redis-instance as i get AUTH-messages in my Redis-instance, but i don't get any GET, SET or DELETE-messages, and the log of Redis says:

![image](https://user-images.githubusercontent.com/5573149/222918953-5b09c9a8-2705-4c85-b4df-ee320564cf42.png)

This is the settings used:
```
redisCacheEnabled: true

redisCacheHost: Redis:6379

redisCachePassword: REDACTED

logLevel: DEBUG
```

**Comment by Allram** [comment]
It seems like it hangs on GetDecision from the Rediscache as the device i try to login to from an external ip just hangs on loading when Redis is enabled:
![image](https://user-images.githubusercontent.com/5573149/222919386-12abc304-1182-416d-b281-9a0e32301d58.png)

**Comment by mathieuHa** [comment]
Hi @Allram,

We'll take a look and get back to you quickly

**Comment by mathieuHa** [comment]
Hi @Allram,

We found a bug in simple-redis and fixed it.
Redis password is till in beta at the moment.

Could you upgrade to `v1.1.11-beta2` and tell us if it fixes your issue ?

Best,
Mathieu

**Comment by Allram** [comment]
Works perfectly! 
Added some blocklists from Crowdsec, and my Redis instance DB:0 filled with 60k keys instantly.
Testet LIVE mode and it adds the IP's that are doing requests if they are not in the RedisCache and says "cache:hit" in the logs :)

**Comment by mathieuHa** [comment]
Glad to know it worked out :)
